name: json_shrink_widget
description: A widget to format json,support developer have a beatiful json viewer.

homepage: https://github.com/fastcode555/json_viewer.git
version: 1.1.5

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/icon_add.png
    - assets/icon_minus.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg